#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo $DIR/lib/jmagick/lib/:$DIR/lib/gson.jar
java -Xmx6g -Djava.library.path="$DIR/lib/jmagick/lib/" -cp "bin:$DIR/lib/gson.jar" svh.portship.Portship "$@"
